### ISSUE TITLE
Make `getHarness(MyHarness)` re-usable between invocations and expectations

### ISSUE THREAD

**Issue by edbzn** [jscutlery/test-utils#3]
We can call our self `getHarness()` or `getAllHarnesses()` on each invocations or expectations. 

- [ ] `should`
- [ ] `invoke`

It would simplify the test and make it more understandable for new comers by hiding apparent complexity.

**Comment by yjaaidi** [comment]
Actually, I think we should implement a command, e.g. `cy.getHarness` and use alises in our examples. There is a lint rule that enforces the cypress best practice of not using variables: https://docs.cypress.io/guides/references/best-practices.html#Assigning-Return-Values

If we head in this direction, we have to fix this first: https://github.com/angular/components/issues/20871#issuecomment-733804928 but there might be some other instanceof issues elsewhere.

We have to think about other more complex scenarios like: `getHarness(DatePicker).pipe(harness => harness.getCalendar())`
That's where we can see that aliases are a better fit as otherwise we'll be reinventing our own aliasing system somehow.

@edbzn what do you think?

**Comment by edbzn** [comment]
> Actually, I think we should implement a command, e.g. cy.getHarness and use alises in our examples. There is a lint rule that enforces the cypress best practice of not using variables: https://docs.cypress.io/guides/references/best-practices.html#Assigning-Return-Values

That's sound good, it's more aligned with Cypress philosophy and commands are easily callable, no need to import something. How we could name these aliases, do we keep the Harness terminology as it is? I keep in mind that we could simplify Harness usage.

 > If we head in this direction, we have to fix this first: angular/components#20871 (comment) but there might be some other instanceof issues elsewhere.
 
Agree it's related to the chainable API, we could wait the [proposed solution](https://github.com/angular/components/issues/21183) lands in an official release, or we could provide it our self in advance. 

> We have to think about other more complex scenarios like: getHarness(DatePicker).pipe(harness => harness.getCalendar())
That's where we can see that aliases are a better fit as otherwise we'll be reinventing our own aliasing system somehow.

Agree, aliases will be a good fit here. For now I just explored the basic scenario:

```ts
it('should setInputValue', () => {
  getRootHarness(TestedHarness).invoke('setValue', 'test');
  getRootHarness(TestedHarness).invoke('getValue').should('equal', 'test');
});
```

Changed into: 

```ts
it('should setInputValue', () => {
  getRootHarness(TestedHarness).invoke('setValue', 'test').invoke('getValue').should('equal', 'test');
});
```

If the `TestedHarness#invoke(...)` and `TestedHarness#should(...)` methods await the `TestedHarness#host()` result, it should make the chainable API work. Am I missing something? :thinking:

**Comment by srlee309** [comment]
To reduce the repetition in the harness creation the simplest solution is a shared function. For example,
`export const exampleForm = () => getHarness(ExampleFormHarness);`

The below is an example test: https://github.com/srlee309/component-commands-example/blob/master/libs/example/form/.cypress/src/integration/storybook/form-component-test-harness.spec.ts
```
it('should show submit button and model values when they are entered', () => {
    exampleForm().its('submitButton').should('be.disabled');
    exampleForm()
      .typeName('test')
      .typeAlterEgo('test')
      .selectPower(HeroPower.superFlexible);
    exampleForm().its('submitButton').should('be.enabled');
    exampleForm().its('modelName').should('eq', 'test');
    exampleForm().its('modelAlterEgo').should('eq', 'test');
    exampleForm().its('modelPower').should('eq', HeroPower.superFlexible);
  });
```

I noticed that getHarness gave lint errors when I tried:
```
  exampleForm()
      .typeName('test')
      .typeAlterEgo('test')
```
After updating it to the below type it worked. 
```
export declare function getHarness<T extends ComponentHarness>(query: HarnessQuery<T>): 
Cypress.Chainable<T> & ReturnType<T>;

type ReturnType<T> = { [K in keyof T]: (...args: any) => ReturnType<T>};
```
The type could be improved ,e.g. it could only get the methods. 

One area I am not sure on is when you want to select an element, e.g. selected the second row in a table, and then do further operations on it. I think a common use case will be selecting a different test harness from inside another test harness. In this case, the type should change to the new harness and it should be able to be do this without needing a new chain.

**Comment by yjaaidi** [comment]
Currently, the library generates a dynamic wrapper and tries to type it as well as we can in order to allow a usage like `getHarness(...).typeName(...)`. AFAIK, there is currently no way to get perfect typing with this approach so we will just remove the wrapper and the recommended alternatives will be:

```ts
getHarness(...).invoke('typeName', ...)
getHarness(...).pipe(harness => harness.typeName(...));
``` 

Using shared functions and class properties are a great workaround!

**Comment by srlee309** [comment]
If you do the below, I am not getting types on the second invoke as the type is Cypress.Chainable<Promise<ExampleFormHarness>>
`getHarness(...).invoke('typeName', ...).invoke('typeAlterEgo', ...)`

Our approach to create something similar to a test harness has been to create cypress custom commands for a component. We use the below custom commands to interact with the component commands. https://github.com/srlee309/component-command-utils/blob/main/commands.ts. These custom commands have been the best way for us to get the right types.

prop - returns a specified property in the component command. It's usage is similar to the 'its' command, but allows the usage of cypress commands in the component command getter function
map - returns the result of a component command function. Its usage is similar to the 'invoke' command, but allows the usage of cypress commands in the component command function
tap - executes a component commands function and returns the calling component command. This allows the chaining of actions on the same component command.

Example: 
- test https://github.com/srlee309/component-commands-example/blob/master/libs/example/form/.cypress/src/support/component-command.ts
- component command https://github.com/srlee309/component-commands-example/blob/master/libs/example/form/.cypress/src/support/component-command.ts
