### ISSUE TITLE
Is it possible to do cy.intercept of api call for angular application in new cypress component test runner

### ISSUE THREAD

**Issue by Sathish787** [jscutlery/test-utils#43]
Is it possible to do cy.intercept of api call for angular application in new cypress component test runner.

I watched new cypress component test runner video where api call intercepted and data are mocked for React component. 

Is same behaviour available for angular too?

**Comment by edbzn** [comment]
Well, I think it should work as described in the documentation also for Angular since it relies on proxies, let me know if you struggle.
