### ISSUE TITLE
Is installing NX (ng add @nrwl/workspace) mandatory for these library to work

### ISSUE THREAD

**Issue by Sathish787** [jscutlery/test-utils#45]
Looks like adding @nrwl/workspace completely changes the project structure which I cannot afford. Already our application is very complex and cannot afford to restructure and peers would not accept it.

Let me know whether this cypress unit test library works without adding @nrwl/workspace

Thanks
Sathish

**Comment by edbzn** [comment]
Our packages are not directly dependent on Nx so you can use them without @nrwl/workspace, but Nx would help you to scaffold common configurations correctly, including E2E tests using Cypress. I used Cypress without Nx a long time ago and I remember it was a headache, the witness is your pain right now.

In other words, you don't absolutely need Nx, but I can't help you without it.

**Comment by edbzn** [comment]
I'll close this, our goal is to support both Nx & regular Angular CLI, no Nx dependency mandatory.
