### ISSUE TITLE
`nx run my-app:e2e --testingType component` does not work for an `@nrwl/nx`-generated project

### ISSUE THREAD

**Issue by rkrisztian** [jscutlery/test-utils#63]
I've got an Angular 12 project set up with `@nrwl/nx` version 12.3.6. It has two projects: `my-app` (for the Angular app itself) + `my-app-e2e` (for the Cypress end-to-end tests). To add Cypress component testing too, I've followed the README:

```none
npx ng add @jscutlery/cypress-angular
```

By the way, this adds the package as a regular dependency, instead of a dev dependency. Bug? Anyways, I've moved it into the dev dependencies, it shouldn't matter anyway.

```none
npx ng g @jscutlery/cypress-angular:setup-ct --project my-app
npx ngcc
```

The following command failed: ❌

```none
$ npx nx run my-app:e2e --testingType component
An unhandled exception occurred: Project target does not exist.
See "/tmp/ng-Wpsu5T/angular-errors.log" for further details.
```

The following command worked and executed the sample tests successfully: ✔

```none
$ npx cypress open-ct --project apps/my-app
```

However, if I add the following to `angular.json`, I can fix the `nx` way like this:

```js
{
  // ...
  "projects": {
    "my-app": {
      // ...
      "architect": {
        // ...
        "ct": {
          "builder": "@nrwl/cypress:cypress",
          "options": {
            "cypressConfig": "apps/my-app/cypress.json",
            "tsConfig": "apps/my-app/tsconfig.cypress.json",
            "devServerTarget": "",
            "testingType": "component"
          }
        }
      }
    }
    // ...
  }
}
```

Then the command simply becomes: ✔

```none
$ npx nx run my-app:ct
```

I guess it makes sense to add something like this to the documentation or to the schematic?

**Comment by rkrisztian** [comment]
This issue might be related to https://github.com/jscutlery/test-utils/issues/49

**Comment by rkrisztian** [comment]
I don't know if I should open a ticket about this, but in an `@nwrl/nx`-generated project, the Cypress **video and screenshot paths are not configured** for component tests by the schematic, I had to do it myself **so that the videos are automatically git ignored**:

https://github.com/rkrisztian/cypress-jest-test-project/commit/2f18cd4d01224956f41f4413e988a5ca0522a54c#diff-ff33022ba6f5c96693402adef8688371518e9ddcf5b5f10cfa0605833709efd6

I'm wondering if we can pick up some Nx conventions here when use of Nx is detected.

**Comment by edbzn** [comment]
Hi, sorry for the delay. I removed the mention of this Nx command in the doc because as you mentioned the workspace definition is not updated accordingly by the schematic. To make this feature, before we have to make the function [`updateProjectConfiguration`](https://github.com/nrwl/nx/blob/0c454dd29f28df535bff87c8bfac08f85e9dd8c1/packages/devkit/src/generators/project-configuration.ts#L48) compatible with regular  AngularCLI, see:  https://github.com/nrwl/nx/issues/5678.

> I don't know if I should open a ticket about this, but in an @nwrl/nx-generated project, the Cypress video and screenshot paths are not configured for component tests by the schematic, I had to do it myself so that the videos are automatically git ignored:

I think it's another issue, let's open a new ticket.
