### ISSUE TITLE
Cypress 7 and beyond & Angular 13 support

### ISSUE THREAD

**Issue by BrkCoder** [jscutlery/test-utils#76]
@yjaaidi Hey How are you ?
I would like to know if you are going to support angular 13 & cypress 7+ and beyond
in the future ?
is it a long term support ? Can we rely on this package for our internal tests in the company ?

**Comment by edbzn** [comment]
> I would like to know if you are going to support angular 13 & cypress 7+ and beyond
in the future ?

Hi, sure we want to support next Angular and Cypress versions.

> is it a long term support ? Can we rely on this package for our internal tests in the company ?

No, we have no long-term support engagements, this project is maintained in our free time between other open-source projects.
