### ISSUE TITLE
Convert libs to standalone projects

### ISSUE THREAD

**Issue by edbzn** [jscutlery/test-utils#93]
"Fewer merge conflicts, more precise affected operations, easier to grasp."

```bash
nx generate @nrwl/workspace:convert-to-nx-project --all
```

**Comment by Jefiozie** [comment]
Happy to make a PR for this issue if you don't mind

**Comment by edbzn** [comment]
@Jefiozie Sure, go ahead!

**Comment by Jefiozie** [comment]
HI @edbzn, added PR #96  to resolve this issue.
